---
deployment:
  tasks:
    - export REPO=~/repositories/albahja-electricity
    - export WEB=/home/albaqifg/public_html
    - /bin/find $WEB -mindepth 1 -not -path "$WEB/uploads*" -delete
    - /bin/cp -R $REPO/public/. $WEB/
    - /bin/cp -R $REPO/app /home/albaqifg/
    - /bin/cp -R $REPO/database /home/albaqifg/
    - /bin/cp -R $REPO/storage /home/albaqifg/
    - /bin/cp $REPO/.htaccess /home/albaqifg/
    - /bin/mkdir -p /home/albaqifg/storage/logs
    - /bin/chmod 755 /home/albaqifg/storage/logs
    - /bin/chmod 755 $WEB/uploads
